create database Libary_Management;
use Libary_Management;

show tables;
select * From books;
describe  books;
select * From branch;
describe  branch;
select * from employees;
describe  employees;
select * From issued_status;
select * From return_status;
describe  issued_status;
select * from  members;
describe  members;
select * from return_status;
describe return_status;

ALTER TABLE branch 
MODIFY branch_id VARCHAR(20);

ALTER TABLE employees 
MODIFY branch_id VARCHAR(20);

ALTER TABLE employees 
MODIFY emp_id VARCHAR(20);

ALTER TABLE books 
MODIFY isbn VARCHAR(20);

ALTER TABLE members 
MODIFY member_id VARCHAR(20);

ALTER TABLE issued_status 
MODIFY issued_id VARCHAR(20);

ALTER TABLE return_status 
MODIFY return_id VARCHAR(20);

ALTER TABLE issued_status
MODIFY issued_id VARCHAR(20);

ALTER TABLE issued_status
MODIFY issued_member_id VARCHAR(20);

ALTER TABLE issued_status
MODIFY issued_book_isbn VARCHAR(20);

ALTER TABLE issued_status
MODIFY issued_emp_id VARCHAR(20);

Alter table return_status
modify issued_id varchar(20);

Alter table return_status
modify return_book_isbn varchar(20);



-- ADD primary key 

ALTER TABLE books 
ADD PRIMARY KEY (isbn);

ALTER TABLE branch
ADD primary key (branch_id);

alter table employees
ADD primary key (emp_id);

Alter table issued_status
add primary key (issued_id);

ALTER TABLE members
add primary key (member_id);

ALTER TABLE return_status
add primary key (return_id);

-- Add foregin key
ALTER TABLE employees
add FOREIGN KEY (branch_id)
REFERENCES branch(branch_id);

ALTER TABLE issued_status
add FOREIGN KEY (issued_member_id)
REFERENCES members(member_id);

ALTER TABLE issued_status
add FOREIGN KEY (issued_book_isbn)
REFERENCES books(isbn);

ALTER TABLE issued_status
add FOREIGN KEY (issued_emp_id)
REFERENCES employees(emp_id);

alter table return_status
add constraint fk_issued_id
foreign key (issued_id)
references issued_status(issued_id);

select i.issued_id, r.issued_id
from issued_status i
right join return_status r
on i.issued_id = r.issued_id;


delete 
FROM return_status
WHERE issued_id NOT IN (
    SELECT issued_id FROM issued_status
);
SET SQL_SAFE_UPDATES = 0;
-- fill null values of book id and book name from parent table issued status
update return_status r
join issued_status i on r.issued_id = i.issued_id
set r.return_book_isbn = i.issued_book_isbn
where r.return_book_isbn is null;

update return_status r
join issued_status i on r.issued_id = i.issued_id
set r.return_book_name = i.issued_book_name
where r.return_book_name is null;

alter table return_status
add foreign key (return_book_isbn)
references books(isbn);

describe issued_status;

-- Create a new book record
INSERT INTO books (isbn, book_title, category, rental_price, status, author, publisher)
VALUES ('978-0131103627', 'The C Programming Language', 'Education', 7.50, 'Available', 'Kernighan & Ritchie', 'Prentice Hall');
 
-- Update an existing member's address
select*from members;
update members
set member_address = 'LRI Marg'
where member_id = 'C105';

-- Delete a record from the issued status table 
select * from issued_status;
delete from issued_status
where issued_id = 'IS140';

-- Retrieve all book issued by an employee 
select * From issued_status
where issued_emp_id = 'E105';

-- List employee  who have issued more than 1 book 
select issued_emp_id,count(issued_id) as total_issued
from issued_status
group by issued_emp_id
having total_issued > 1;

-- create a summary table used CTAS to generate new tables based on each book and book issued count
Create table book_count
as
select b.book_title,count(i.issued_book_isbn) as total_issued
from books as b
join issued_status as i
on b.isbn= i.issued_book_isbn
group by b.book_title;
select * From book_count;

-- retrive all the  books from specific category
select * From books
where category = 'Fantasy';

-- Total rental income generated by each category
select b.category,sum(b.rental_price) as total_income,count(*) as total_issued
from books as b
join issued_status as i
on b.isbn = i.issued_book_isbn
group by b.category;

-- list the member who has registered in last 180 days
insert into members(member_id,member_name,member_address,reg_date)
values
('C120','Hella','Kalanki','2026-01-05'),
('C121','Harry','Pulchowk','2026-02-06'),
('C122','Shubham','Baisiparty','2025-12-30');
select * from members
where reg_date >= NOW() - interval 180 day;

-- list the employees with their branch manager and their branch detail
select e1.*,e2.emp_name as manager_name,b.branch_address From employees as e1
join branch as b
on e1.branch_id = b.branch_id
join employees as e2
on b.manager_id =e2.emp_id
;
select * From branch;

-- create a table of book rental prices more than 7
create table high_price_books
as
select * From books
where rental_price >= 7;

select * from high_price_books;

-- retrieve all the books that has not been returned 
select distinct i.issued_book_name as not_return From issued_status as i
left join return_status as r
on i.issued_id = r.issued_id
where r.issued_id is null;



